
title: Pathum Egodawatta
email: pathum@mooniak.com
description: >-
  Interdisciplinary designer, thinker, and catalyst working at the
  intersections of type, text, design, code, and culture.
baseurl: ""
url: "https://pathumego.com"
github_username: pathumego

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

plugins:
  - jekyll-feed
